### ISSUE TITLE
error with destroy when component unmounts 

### ISSUE THREAD

**Issue by KevinOl** [datatrans/payment-button#11]
Hi,

in my useEffect I have the following,

```
useEffect(() => {
...

   return () => {
       paymentButton.destroy()
   }
}, [...])
```

when the component unmounts I am getting the following error in console,

```
Uncaught TypeError: Cannot set property 'innerHTML' of undefined
    at Object.ie [as destroy] (payment-button-1.0.0.js:255)
```

I don't get this when I return only () => {}

Idea? Setup same as usual Google and Apple pay.

**Comment by pstadler** [comment]
This is a question related to your unmerged PR. I can't reproduce this by toggling the `PaymentButtonWithHook` component. Let's close this issue and continue in your PR

**Comment by pstadler** [comment]
After further testing I was able to reproduce it. Will put a statement regarding this in your PR.
