### ISSUE TITLE
No wallet available on iphone

### ISSUE THREAD

**Issue by KevinOl** [datatrans/payment-button#12]
Hi there,

apple pay button is not displayed on my iphone. When checking the console log I see 'no wallet available' from the unsupported listener.
However, wallet is set with all credit cards. I tried on other websites implementing apple pay and I saw this button.

Also, window.AppleSession and window.AppleSession.canMakePayments() passed.

Idea?

**Comment by KevinOl** [comment]
Actually, I needed to register the domain for Apple Pay in datatrans webadmin panel. Now it is working.

The error message is a bit misleading though.

**Comment by fgrDtrx** [comment]
Hi @KevinOl , thats correct for Apple Pay you need to register your domain. Unfortunately we are not able to check if a domain has been registered with the Apple APIs. The reason for the error message is that we use `canMakePaymentWithActiveCard` (which requires a domain registration), which returns false in 2 cases: 1. there is no card available 2. the domain is not registered. Hence we can not differentiate.
