### ISSUE TITLE
Whitelist domain starting with http, https

### ISSUE THREAD

**Issue by kapcabbage** [datatrans/payment-button#23]
Hey Datatrans team!

It looks like there is no way to whitelist any domains that are not in format: **www.{url}.** Resulting in this error  
`Access to fetch at 'https://pay.sandbox.datatrans.com/upp/wallets/auth' from origin 'https://{url}' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Can you guide me how to overcome this issue?

**Comment by dmengelt** [comment]
Hi @kapcabbage 
In order to help you on this issue we need your merchantId. Its best if you reach out to support@datatrans.ch
