### ISSUE TITLE
React integration

### ISSUE THREAD

**Issue by KevinOl** [datatrans/payment-button#5]
Could you provide an example of how to integrate this with react?

**Comment by dmengelt** [comment]
Hi @KevinOl 
We are working on an example for react. We will let you know once it is available.

**Comment by dmengelt** [comment]
@KevinOl here you go: https://github.com/datatrans/payment-button/tree/master/react-example

**Comment by KevinOl** [comment]
I created a hook but cannot make a pull request. Is there a way you could allow me to?

**Comment by pstadler** [comment]
You need to push your changes to a branch on a fork.
