### ISSUE TITLE
paymentButton destroy not defined

### ISSUE THREAD

**Issue by KevinOl** [datatrans/payment-button#8]
Hi, 

I've noticed that when calling

`paymentButton.destroy()`

an error is thrown because destroy is not defined on paymentButton.

Is it missing from the implementation or?

**Comment by fgrDtrx** [comment]
Hi @KevinOl, 

Thanks for the hint. `destroy() `was not defined. We will push a new version soon to address this issue.

**Comment by fgrDtrx** [comment]
Hi @KevinOl, we have released the new version containing the `destory()` method.
