### ISSUE TITLE
Event listener onError goes ballistic

### ISSUE THREAD

**Issue by KevinOl** [datatrans/payment-button#9]
Hi,

debugging and handling errors locally with

`paymentButton.on("error", () => {});`

When errors are thrown the event listener goes into an infinite call and crashes my safari/chrome. It is asif something is being re-triggered (call to apple or google pay?) from the payment button js file. Therefore, call/error, call/error...

I am not sure where to call paymentButton.off('error'). I tried immediately inside onError but...not sure if that is where it should be.

Suggestion?

**Comment by fgrDtrx** [comment]
Hi @KevinOl, 

I was not able to reproduce this one. Can you describe what configuration (init and create methods) you are using and what error is thrown?

**Comment by KevinOl** [comment]
Hi @fgrDtrx,

basically I wanted to check what paymentButton.on('error', error => console.log(error)) was giving me back.

So, I decided to test without https. Error message is: "DEVELOPER_ERROR in isReadyToPay: Google Pay APIs should be called in secure context!".

As a result, paymentButton.on('error', error => console.log(error)) is triggered non-stop until safari/chrome crashed.

init config (passing merchantId and name later):

```
const DEFAULT_OPTIONS = {
	useGooglePay: false,
	useApplePay: false,
	auto: true,
	autoSettle: false,
	tokenOnly: false,
	allowedCardNetworks: [
		PAYMENT_METHOD_CREDITCARD_VISA,
		PAYMENT_METHOD_CREDITCARD_MASTERCARD,
		PAYMENT_METHOD_CREDITCARD_AMEX,
	],
	googlePayConfiguration: {
		buttonType: 'long',
		buttonStyle: 'black',
	},
	applePayConfiguration: {
		buttonType: 'plain',
		buttonStyle: 'black',
	},
}
```

payment request:

```
details: {
		total: {
			label: 'Test label',
			amount: { value: amount, currency },
		},
	},
	options: {
		requestPayerEmail: false,
		requestPayerName: false,
		requestPayerPhone: false,
		requestShipping: false,
	},
	transaction: {
		countryCode: 'CH',
		refno,
	}
```

**Comment by fgrDtrx** [comment]
Hi @KevinOl 

this is strange. I was not able to reproduce this error. The error was only fired once for me. Can you confirm the issue persists with the new version?

**Comment by KevinOl** [comment]
Hi @fgrDtrx 

so I tried again with the onError listener enabled, same setup and it was fine this time. I guess the new version fixed something.

If this occurs again I will be back ;-)

Thanks for your help.
